github:
  username: bedder
timezone: Europe/London
email: matthew@bedder.co.uk
mailto: mailto:matthew@bedder.co.uk

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Matthew Bedder"

exclude:
  - "*.psd"
  - "*.ai"

gems:
  - jekyll-redirect-from

sass:
  style: compressed