github:
  username: bedder
timezone: Europe/London
email: matthew@bedder.co.uk
mailto: mailto:matthew@bedder.co.uk

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Matthew Bedder"

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

sass:
  style: compressed

paginate: 5
paginate_path: "/blog/page:num/"

exclude: ["README.md", "CNAME"]