github:
  username: bedder
timezone: Europe/London
email: matthew@bedder.co.uk
mailto: mailto:matthew@bedder.co.uk

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"
      author: "Matthew Bedder"
